### ISSUE TITLE
[improvement] use google drive api to only request sheet data if the source was updated

### ISSUE THREAD

**Issue by robertvasile** [athersharif/metis#12]
got a new one for ya :) i started to implement it myself, but these days i lack spare time for personal projects

how about requesting sheet data ONLY if the local data timstamp differs from the last updated one in the cloud?
google sheets api does not support it, but it can be done with google drive api

so, basically, implementing it would mean to 
1. always request the last updated timestamp from drive api
2. store the timestamp locally
3. check local timestamp against the one received via gdrive api
4. load data:
  4.a. if the same, load locally stored sheet data
  4.b. if different, request cloud sheet data

what do you think?

PS. i found some similar issue searching around other implementations, found this thread to be a good starting point:
https://github.com/googleapis/google-api-nodejs-client/issues/635

**Comment by athersharif** [comment]
@robertvasile (sorry, i was away for a bit) what a wonderful idea! tagging this for this next release.

**Comment by charlau** [comment]
It seems like this project has been on pause for 2 years, but that feature would be awesome!

**Comment by athersharif** [comment]
> It seems like this project has been on pause for 2 years, but that feature would be awesome!

sorry, i keep getting sidetracked. it is on my list to address!

**Comment by athersharif** [comment]
apologies for delay here. finally released this feature in the latest release https://github.com/athersharif/metis/releases/tag/3.0.0. thanks for the suggestion!
