### ISSUE TITLE
Legacy context API update

### ISSUE THREAD

**Issue by albertoSoto** [athersharif/metis#13]
Last React version shows this big warning while using it:

Warning: Legacy context API has been detected within a strict-mode tree.
The old API will be supported in all 16.x releases, but applications using it should migrate to the new version.
Please update the following components: GoogleSheetsProvider

**Comment by athersharif** [comment]
thanks for reporting @albertoSoto. tagged this for next release. feel free to check back in on this issue for updates.

**Comment by athersharif** [comment]
apologies for the delay here. https://github.com/athersharif/metis/releases/tag/2.2.0 resolves this issue. thanks again for reporting the issue!
