### ISSUE TITLE
[Documentation request] read only access

### ISSUE THREAD

**Issue by braco** [athersharif/metis#14]
Should be clearer that this is read-only access to the sheet and that there are some alternatives that allow write access, like:

https://www.npmjs.com/package/react-google-sheets
https://github.com/theoephraim/node-google-spreadsheet

**Comment by sometimescasey** [comment]
Thank you. I too was looking for something that would allow read as well as write...please make this clearer in the documentation!

Thanks to the creator for their hard work - this works well for read-only but unfortunately this does not fit my use case.

**Comment by athersharif** [comment]
thanks for the issue and apologies for the delay. the readme now displays the disclaimer!
