### ISSUE TITLE
How do we use the data in the component?

### ISSUE THREAD

**Issue by newt0** [athersharif/metis#15]
Thanks for great library!

I can have got the data from Google Sheets by setting `<GoogleSheetsProvider>` in `App.js`.
Now I can see the data as `state` on the browser via React Developer tools(Chrome extension).
![image](https://user-images.githubusercontent.com/56229817/107458681-e8820180-6b97-11eb-8a8a-a79023e5f9ca.png)

But I can't use the data like rendering it or display it by `console.log`. 

How do we use the data in the component?
I tried it with the Docs, but I can't have understood it.

**Comment by athersharif** [comment]
@newt0 you'd want to use the `withGoogleSheets` HOC to access the data. check out the relevant import example here: https://github.com/athersharif/metis/blob/master/example/src/SingleSheet.js#L47

**Comment by newt0** [comment]
Thank you for your reply!

I fixed `SingleSheet.js` below. 

``` 
import React from "react";
import PropTypes from "prop-types";
import { withGoogleSheets } from "react-db-google-sheets"; 

const SingleSheet = (props) => (
  <div>
    <table className="table">
      <thead>
        <tr>
          <th>id</th>
          <th>name</th>
          <th>email</th>
        </tr>
      </thead>
      <tbody>
        {props.db.samplesheet.map((data) => (
          <tr key={data.id}>
            <td>{data.id}</td>
            <td>{data.name}</td>
            <td>{data.email}</td>
          </tr>
        ))}
      </tbody>
    </table>
    <button className="btn btn-primary" onClick={props.refetch}>
      Refresh
    </button>
  </div>
);

SingleSheet.propTypes = {
  db: PropTypes.shape({
    samplesheet: PropTypes.arrayOf(PropTypes.object),
  }),
};

export default withGoogleSheets("samplesheet")(SingleSheet);
```

And trying to use `<SingleSheet>` in `App.js`.
But it has the error.

![image](https://user-images.githubusercontent.com/56229817/107751718-1bc3bc80-6d61-11eb-9132-b5f63615f038.png)

It means that [the google sheets](https://docs.google.com/spreadsheets/d/1h3lSahG8BHHv7nhYFvctyv32Sf9MQBcCRCBk3gZdNOk/edit?usp=sharing), which I use, has something wrong?

**Comment by athersharif** [comment]
@newt0 there are a few things to test:

1. have you set up the API key as mentioned [here](https://github.com/athersharif/metis#getting-the-api-key)? (please don't share the API key)
2. have you added the keys to the .env file as mentioned [here](https://github.com/athersharif/metis#specifying-doc-id-and-api-key)? **and then restarted the React app?**
3. does the doc id match the one from your google doc? (your google sheets looks fine)
4. what do you see in the console? any errors? could you try logging the `props` to see what you're getting there?

**Comment by newt0** [comment]
I appreciate a lot!

>1.have you set up the API key as mentioned here?

Yes, I got it.
![image](https://user-images.githubusercontent.com/56229817/107763338-d65bbb00-6d71-11eb-8c91-ea6ea238b625.png)
![image](https://user-images.githubusercontent.com/56229817/107763425-f7241080-6d71-11eb-900d-11849e1a1c3a.png)

> 2.have you added the keys to the .env file as mentioned here? and then restarted the React app?

Yes, I set the `.env` file on the root. And restarted the local server.

```
REACT_APP_GOOGLE_SHEETS_API_KEY="My API Key"
```

> 3. does the doc id match the one from your google doc? (your google sheets looks fine)
Yes.

```
REACT_APP_GOOGLE_SHEETS_DOC_ID="1h3lSahG8BHHv7nhYFvctyv32Sf9MQBcCRCBk3gZdNOk"
```

**Comment by newt0** [comment]
> 4. what do you see in the console? any errors? could you try logging the props to see what you're getting there?

![image](https://user-images.githubusercontent.com/56229817/107763936-b37dd680-6d72-11eb-9833-ec471e2e11fc.png)

![Uploading image.png…]()

**Comment by athersharif** [comment]
that's helpful! thanks for the screenshots. could you try the setting the env variables without the `"` (quotation marks)?

for example:

```
REACT_APP_GOOGLE_SHEETS_DOC_ID=1h3lSahG8BHHv7nhYFvctyv32Sf9MQBcCRCBk3gZdNOk
```

and then restart the React app? if the problem persists, do you have a repo up that i could take a look at?

**Comment by newt0** [comment]
Thank you for your nice answer!

>could you try the setting the env variables without the " (quotation marks)?

I set the env variables without the `""` like below.

```
REACT_APP_GOOGLE_SHEETS_API_KEY=MY_API_KEY
REACT_APP_GOOGLE_SHEETS_DOC_ID=1h3lSahG8BHHv7nhYFvctyv32Sf9MQBcCRCBk3gZdNOk
```

And then restarted, the same problem persits.

![image](https://user-images.githubusercontent.com/56229817/107847538-cbfff680-6e2f-11eb-8b31-158beba33b45.png)

But I got some things.(Next message)

**Comment by newt0** [comment]
I comment out the code about `map method` in `SingleSheet.js` like below.

```
 <tbody>
        {/* {props.db.samplesheet.map((data) => (
          <tr key={data.id}>
            <td>{data.id}</td>
            <td>{data.name}</td>
            <td>{data.email}</td>
          </tr>
        ))} */}
      </tbody>
```

![image](https://user-images.githubusercontent.com/56229817/107847583-2dc06080-6e30-11eb-8a8b-61f2538dbd2a.png)

And then succeeded  rendering the screen, but the same error occurred.
(`index.js:1 [METIS]: data for samplesheet was empty `)

By checking `React Developer Tools` of the chrome extension, `<GoogleSheetsProvider>` has the data.
Meanwhile, `<SingleSheet>` has no data.
![image](https://user-images.githubusercontent.com/56229817/107848411-9e6a7b80-6e36-11eb-86c3-8cf70e07ad81.png)

![image](https://user-images.githubusercontent.com/56229817/107848435-c3f78500-6e36-11eb-8d3e-6978bc245ebd.png)

I maybe have to pass the `props` to `<SingleSheet>` in `App.js`?
Now, I write `App.js` like below.

```
const App = () => (
  <GoogleSheetsProvider>
    <div className="container">
      <h1>Metis Examples</h1>
      <div className="section">
        <h2>Single Sheet Example</h2>
        <SingleSheet />
      </div>
    </div>
  </GoogleSheetsProvider>
);
```

**Comment by newt0** [comment]
And also, by checking `React Developer Tools` of the chrome extension, I can see the data from google sheets.
But the google sheet which pass the data is not the one I set  in the env file. 
`REACT_APP_GOOGLE_SHEETS_DOC_ID` looks ignored.
I might have put wrong setting about google cloud platform.

**Comment by newt0** [comment]
Finally, succeeded!  Now it is perfectly working!

It was just a careless mistake.
There were two `.env` file on the `root` and `src`.
I were not aware of it, so I confused.

**Comment by athersharif** [comment]
great! glad you figured it out. for anyone else facing the same issue and getting here, the `.env` file is traditionally placed at the root folder level. but different projects can have different structures. however, the core requirement stays the same -- however you set up the environment variables, they should be accessible through `process.env`.

**Comment by newt0** [comment]
【Not question】
I deeply appreciate it!

By the way, I traslated your medium article about Metis into Japanese.
And published it on the "Qiita" ,which is the largest blog platform for engineer of the Japan(Maybe it's similar to reddit)

https://qiita.com/newt0/items/4039c5662fe41cb95bd3

Thank you for awesome library and being nice, again!

**Comment by athersharif** [comment]
that's awfully nice of you! thanks so much!
