### ISSUE TITLE
How we handle image files in google sheet?

### ISSUE THREAD

**Issue by newt0** [athersharif/metis#16]
I would like to ask about how to handle images using Google Sheet as a database.

In the first method, I inserted the image file directly into the cell of the Google Sheet.
I expected an object return from the Google sheet like `image: {path: string, id: string}`, but it returned empty data.

In the second way, I put the URL of the image as `string` in the cell of the Google sheet.
Then, by specifying it as the value of `src` in the <img/> tag, we can successfully display the image in the React component with the data retrieved from Google Sheets.
![image](https://user-images.githubusercontent.com/56229817/110122554-1d821c80-7e03-11eb-8776-67898f10618b.png)

![image](https://user-images.githubusercontent.com/56229817/110122495-0ba07980-7e03-11eb-98a5-0cf2ec6bb627.png)

For example, how about saving an image in Google Drive and putting its URL in a Google Sheet cell?
I think this way, even a non-engineer can add and update content.

What do you think? Also, is there any other better way?

**Comment by athersharif** [comment]
@newt0 apologies for the delayed response. your second way is the more appropriate way to handle the insertion of images, considering what this library currently supports. you can host your images wherever you like, and use the url in the db, to be passed on to the src attribute of the img tag.
