### ISSUE TITLE
Any sample for updation / addition of rows / cells

### ISSUE THREAD

**Issue by ahmednrana** [athersharif/metis#3]
From your medium post
> Metis is intended as a tool to add/modify/delete content on your website

Are there any samples to add / update / modify cells or rows?

**Comment by athersharif** [comment]
@ahmednrana the addition, modification, and deletion of content is expected to be done via Google Sheets. `metis` itself only performs read operations (and for a very good reason). once you set up your Google Sheet and use `metis` as per instructions, any update to the sheet would reflect automatically on your website.
