### ISSUE TITLE
Netlify Deploy - Data Load Error - API KEY Not Valid

### ISSUE THREAD

**Issue by gnardinosaur** [athersharif/metis#4]
First, thank you for creating and sharing this package - it's been super helpful in a project of mine. 

Second, I have everything working as intended locally but when deployed to [Netlify](https://ecstatic-jang-6cab02.netlify.app/) I receive the below error and am being directed to line 86 in withGoogleSheets.js.

ERROR: 
_**Data Load Error: HTTP Status: 400
API KEY NOT VALID. PLEASE PASS A VALID API KEY.**_

In the project's Google Console I have no restrictions set for the key, the sheet is public, and I've set up my .env file as directed in your README. 

I've tried a few things but can't seem to figure it out. I realize this could likely be an issue on the Netlify side of things but thought I'd ask if you had any ideas on which thread to pull next to find a fix.

Thank you -
Nick

**Comment by gnardinosaur** [comment]
Following up to say I went a different route and found a solution. Please feel free to disregard my question and close the issue. 

Thank you.

**Comment by athersharif** [comment]
hi @gnardinosaur - apologies for the delayed response. got a chance to click on the Netlify app link that you posted above. the network call to Google Sheets there shows:

```
{
  "error": {
    "code": 403,
    "message": "Requests from referer https://sheets.googleapis.com/ are blocked.",
    "status": "PERMISSION_DENIED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.Help",
        "links": [
          {
            "description": "Google developer console API key",
            "url": "https://console.developers.google.com/project/583751769756/apiui/credential"
          }
        ]
      }
    ]
  }
}
```

you might want to whitelist the referrer in your Google Console. hope that helps!

**Comment by gnardinosaur** [comment]
@athersharif - you're correct. Figured out how I had to whitelist my Netlify URL. 

Thank you for following up, and again for the module. 

Nick

**Comment by athersharif** [comment]
great! happy to help!
