### ISSUE TITLE
Is there a way to reload the data?

### ISSUE THREAD

**Issue by anthonnyc2** [athersharif/metis#5]
I'm showing a list with info that I'm getting from a google spreadsheet. But I was wondering if I can add a button in my page that perform a request or something to get the new fresh data from the google sheet instead of refresh the site directly?

**Comment by athersharif** [comment]
@anthonnyc2 i believe what you're asking for is a `refetch` function, which we don't support currently but is a great idea. definitely something for the next version.

a work around this would be to manipulate the state of the container component, forcing it to reload based on an action (such as button click).

**Comment by athersharif** [comment]
merged via #11. queued for next release.

**Comment by athersharif** [comment]
new release ([2.1.0](https://github.com/athersharif/metis/releases/tag/2.1.0)) has been published and has this feature. update your package to this version for the feature. 

thanks for the feature request, and feel free to submit a new issue if you come across an odd behavior or have more suggestions!
