### ISSUE TITLE
[improvement] change "Loading..." div in provider to a configurable component

### ISSUE THREAD

**Issue by robertvasile** [athersharif/metis#7]
using react-db-google-sheets with any decent UI and any large dataset from GSheets it's a visual pain, as there's no way to customize the plain div for the loading state w/o modifying the core module

how about adding a config option to pass a custom component for loading?

**Comment by athersharif** [comment]
@robertvasile great idea! planning on supporting that feature in the next release.

**Comment by athersharif** [comment]
merged via #9. queued for next release.

**Comment by athersharif** [comment]
new release ([2.1.0](https://github.com/athersharif/metis/releases/tag/2.1.0)) has been published and has this feature. update your package to this version for the feature. 

thanks for the feature request, and feel free to submit a new issue if you come across an odd behavior or have more suggestions!

**Comment by robertvasile** [comment]
you need to update the docs, there's an error there (probably from c/p the text block)
_**dataLoading**_ instead of _**dataLoadError**_

![image](https://user-images.githubusercontent.com/4264827/87881517-67e49380-ca02-11ea-87c0-fc957916d993.png)

**Comment by athersharif** [comment]
darn, great catch. oversight on my part. should be fixed now.
